### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by hayleyxyz** [ashegoulding/webglgears#2]
Result in Firefox:

<img width="748" alt="webglxgears" src="https://user-images.githubusercontent.com/7829319/42718654-b4a84972-8702-11e8-8c4a-ce59c6bad0e2.png">

As I have very little knowledge in GL, I can't really offer any suggestions on why this may be happening

**Comment by dxdxdt** [comment]
Like what I wrote? Well, I literally used Firefox in the youtube video I linked on the README page. This could be driver related problem. Your screenshot suggests that you ran the demo on a Mac. I've never tested it on Mac, but I have one now, so

## Update
Yup. Just tested on my Mac and found that the demo indeed doesn't run on Firefox for MacOS. I'm guessing:

* GL -> Metal translation goes horribly wrong (ANGLE suddenly decided that it's good idea to do that because, why not? it works perfectly on Windows with DX?)
* Shader precision error

I'll have a look at it when I got time.

Thank you.
