### ISSUE TITLE
Fix a few things discussion.

### ISSUE THREAD

**Issue by Alex313031** [ashegoulding/webglgears#4]
@ashegoulding Hello, if you notice, I have a credits section on https://thorium.rocks/demos.

· WebGL GLXGears - [Fork by Me](https://github.com/Alex313031/webglxgears), originally from [Here](https://github.com/ashegoulding/webglgears). 

That's what it says. I can put your name on there if you'd like.

It is never my intention to not give credit where credit is due, whether on a site or in software. 

What would you like me to change in my fork for you?

And I dont want to transfer ownership of the project. This is all you bud, im just cleaning things up.

Theres literally only two demos on that page tha I made myself. The rest are other people. A few are exactly as they made them, but most of the demos have similar fix ups, like modifying css, adding thumbnails/favicons, etc. A few are heavily modified.

**Comment by Alex313031** [comment]
@ashegoulding Btw how did you port over glxgears to webgl, or did you write it form scratch. I notice it is pure webgl, not three.js or something, props for that.

**Comment by dxdxdt** [comment]
@Alex313031 All good mate.

All I saw from the pull request were just cosmetic changes so I didn't really see the point. You can always use this project as a submodule in your website repo and gift wrap around it if you don't have anything to change in the "engine" code(that's what I would've done anyways).

Direct port between old OpenGL APIs and GLES is technically impossible since all the old APIs are replaced by the use of shaders. If you compare the actual glxgears and my webglgears side by side, you'll notice that the gears don't look the same due to the reasons mentioned in #1. Extra GPU power is needed to achieve the "true look", but I determined that it'd be just an overkill and called it a day(this was a 3-day project).

Yes, I've built it from the scratch with lightweightness in mind because I'd expected to be used as an iframe widget. Look how fast it loads up!

I should probably put a licence on it. Probably Apache 2.0
